const SERVER_URL = "signalwire.com/api";

const TERMS_OF_SERVICE = "https://signalwire.com/legal/signalwire-cloud-agreement";

const CONTACT_NAME = "SignalWire";

const CONTACT_URL = "https://support.signalwire.com/portal/en/newticket?departmentId=1029313000000006907&layoutId=1029313000000074011";

const CONTACT_EMAIL = "support@signalwire.com";

const LICENSE_URL = "https://github.com/signalwire/docs/blob/main/LICENSE";

const LICENSE_NAME = "MIT";

const CONTACT_INFO = #{
  name: CONTACT_NAME,
  url: CONTACT_URL,
  email: CONTACT_EMAIL,
};

const LICENSE_INFO = #{ name: LICENSE_NAME, url: LICENSE_URL };
