import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const c2cSidebar: SidebarsConfig = {
  c2cSidebar: [
    {
      type: "autogenerated",
      dirName: "c2c",
    },
  ],
};

export default c2cSidebar;
