import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const callFlowBuilderSidebar: SidebarsConfig = {
  callFlowBuilderSidebar: [
    {
      type: "category",
      label: "Call Flow Builder",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "call-flow-builder" }],
    },
  ],
};

export default callFlowBuilderSidebar;