import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const clientSdksSidebar: SidebarsConfig = {
  clientSdksSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "sdks/01-overview" }],
    },
    {
      type: "category",
      label: "SDK Reference",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [
        {
          type: "ref",
          id: "sdks/reference/browser-sdk/browser-sdk-reference",
          label: "RELAY Browser SDK",
        },
        {
          type: "ref",
          id: "sdks/reference/realtime-sdk/realtime-sdk-reference-relay",
          label: "RELAY Realtime SDK (Node.js)",
        },
        {
          type: "doc",
          id: "sdks/reference/video-conference-appkit/index",
          label: "Video Conference AppKit",
        },
        {
          type: "ref",
          id: "swml/get-started/index",
          label: "SWML",
        },
      ],
    },
    {
      type: "category",
      label: "SDK Reference (previous versions)",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [
        {
          type: "link",
          label: "RELAY Browser SDK v2",
          href: "https://docs.signalwire.com/reference/relay-sdk-js",
        },
        {
          type: "link",
          label: "RELAY SDK (React Native)",
          href: "https://docs.signalwire.com/reference/relay-sdk-react-native",
        },
        {
          type: "link",
          label: "RELAY SDK (C#)",
          href: "https://docs.signalwire.com/reference/relay-sdk-dotnet",
        },
        {
          type: "link",
          label: "RELAY SDK (Python)",
          href: "https://docs.signalwire.com/reference/relay-sdk-python",
        },
        {
          type: "link",
          label: "RELAY SDK (PHP)",
          href: "https://docs.signalwire.com/reference/relay-sdk-php",
        },
        {
          type: "link",
          label: "RELAY SDK (Go)",
          href: "https://docs.signalwire.com/reference/relay-sdk-go",
        },
        {
          type: "link",
          label: "RELAY SDK (Ruby)",
          href: "https://docs.signalwire.com/reference/relay-sdk-ruby",
        },
        {
          type: "link",
          label: "RELAY SDK (Node.js, deprecated)",
          href: "https://docs.signalwire.com/reference/relay-sdk-nodejs",
        },
      ],
    },
  ],
};

export default clientSdksSidebar;