import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const freeswitchSidebar: SidebarsConfig = {
  freeswitchSidebar: [
    {
      type: "autogenerated",
      dirName: "freeswitch",
    },
  ],
};

export default freeswitchSidebar;
