import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const homeSidebar: SidebarsConfig = {
  homeSidebar: [
    {
      type: "category",
      label: "Welcome",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "home/overview",
        },
      ],
    },

    {
      type: "category",
      label: "Products",
      collapsible: false,
      className: "menu-category",
      items: [

        {
          type: "autogenerated",
          dirName: "home/products",
        },
      ],
    },

    {
      type: "category",
      label: "Platform",
      collapsible: false,
      className: "menu-category",
      items: [
        { type: "autogenerated", dirName: "home/platform" }
      ],
    },

    {
      type: "category",
      label: "Developer Tools",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "home/tools",
        },
        {
          type: "autogenerated",
          dirName: "tools",
        },
      ],
    },

    {
      type: "category",
      label: "Learn",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "link",
          label: "Guides",
          href: "/guides",
        },
        {
          type: "link",
          label: "Changelog",
          href: "/changelog",
        },
        {
          type: "link",
          label: "Community",
          href: "https://signalwire.com/community?utm_source=bobbystable.ai",
        },
        {
          type: "link",
          label: "Support",
          href: "https://support.signalwire.com/hc/en-us",
        },
        {
          type: "link",
          label: "GitHub",
          href: "https://github.com/signalwire",
        },
      ],
    },

  ],

}

export default homeSidebar;