import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const homeSidebar: SidebarsConfig = {
  homeSidebar: [
    {
      type: "autogenerated",
      dirName: "home",
    },
    {
      type: "category",
      label: "Learn",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "link",
          label: "Guides",
          href: "/guides",
        },
        {
          type: "link",
          label: "Community",
          href: "https://signalwire.com/community?utm_source=bobbystable.ai",
        },
        {
          type: "link",
          label: "Support",
          href: "https://support.signalwire.com/hc/en-us",
        },
        {
          type: "link",
          label: "GitHub",
          href: "https://github.com/signalwire",
        },
      ],
    },
  ],
}

export default homeSidebar;