import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const realtimeSdkTechRefSidebar: SidebarsConfig = {
  realtimeSdkTechRefSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default realtimeSdkTechRefSidebar;