import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const realtimeSdkTechRefSidebar: SidebarsConfig = {
  realtimeSdkTechRefSidebar: [
    {
      type: "category",
      label: "Realtime SDK",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "sdks/reference/realtime-sdk" }],
    },
  ],
};

export default realtimeSdkTechRefSidebar;