openapi: 3.0.0
info:
  title: Calling API
  description: |-
    API to create/manage SignalWire's Calls.
    To create a new Call, you send a `POST` request to the Call resource with a payload including a `dial` command and additional nested `params`.
  version: 0.0.0
tags:
  - name: Calls
paths:
  /calls:
    post:
      operationId: Calls_create
      summary: Create a Call
      description: To create a new Call, you send a `POST` request to the Call resource with a payload including a `dial` command and additional nested `params`.
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: string
                enum:
                  - Unauthorized
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                type: string
                enum:
                  - Not Found
        '422':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallCreate422Error'
      tags:
        - Calls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallCreateRequest'
    put:
      operationId: Calls_update
      summary: Update a Call
      description: To update an existing Call, you send a `PUT` request to the Call resource with a payload including an `update` command and additional nested `params`.
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: string
                enum:
                  - Unauthorized
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                type: string
                enum:
                  - Not Found
        '422':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallUpdate422Error'
      tags:
        - Calls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallUpdateRequest'
security:
  - BasicAuth: []
components:
  schemas:
    CallCreate422Error:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Types.StatusCodes.StatusCode422Error'
      example:
        errors:
          - type: validation_error
            code: missing_required_parameter
            message: url must be a valid http or https url
            attribute: url
            url: https://developer.signalwire.com/rest/signalwire-rest/overview/error-codes#http_url_required
    CallCreateParamsSWML:
      type: object
      required:
        - from
        - to
        - swml
      properties:
        from:
          type: string
          description: The address that initiated the call. Can be either a E.164 formatted number (`+xxxxxxxxxxx`), or a SIP endpoint (`sip:xxx@yyy.zzz`).
          example: sip:from-sip@example-112233445566.sip.signalwire.com
        to:
          type: string
          description: The address that received the call. Can be either a E.164 formatted number (`+xxxxxxxxxxx`), or a SIP endpoint (`sip:xxx@yyy.zzz`).
          example: sip:from-sip@example-112233445567.sip.signalwire.com
        caller_id:
          type: string
          description: The number, in E.164 format, or identifier of the caller.
          example: '+1234567890'
        fallback_url:
          type: string
          description: The Fallback URL to handle the call. This parameter allows you to specify a backup webhook or different route in your code containing SWML instructions for handling the call.
          example: https://example.com/fallback
        swml:
          type: string
          description: Inline SWML, passed as a string, containing SWML instructions for handling the call. Either `url` or `swml` must be included for a new call.
          example: "{'version': '1.0.0', 'sections': { 'main': [{ 'answer': { 'max_duration': 60 }},{ 'play': { 'urls': ['silence:2', 'say:Hello from SignalWire!']}}]}}"
      title: Create a call with SWML
    CallCreateParamsURL:
      type: object
      required:
        - from
        - to
        - url
      properties:
        from:
          type: string
          description: The address that initiated the call. Can be either a E.164 formatted number (`+xxxxxxxxxxx`), or a SIP endpoint (`sip:xxx@yyy.zzz`).
          example: sip:from-sip@example-112233445566.sip.signalwire.com
        to:
          type: string
          description: The address that received the call. Can be either a E.164 formatted number (`+xxxxxxxxxxx`), or a SIP endpoint (`sip:xxx@yyy.zzz`).
          example: sip:from-sip@example-112233445567.sip.signalwire.com
        caller_id:
          type: string
          description: The number, in E.164 format, or identifier of the caller.
          example: '+1234567890'
        fallback_url:
          type: string
          description: The Fallback URL to handle the call. This parameter allows you to specify a backup webhook or different route in your code containing SWML instructions for handling the call.
          example: https://example.com/fallback
        url:
          type: string
          description: |-
            The URL to handle the call. This parameter allows you to specify a webhook or different route in your code containing SWML instructions for handling the call.
            Either `url` or `swml` must be included for a new call.
          example: https://example.com/swml
      title: Create a call with a URL
    CallCreateRequest:
      type: object
      required:
        - command
        - params
      properties:
        command:
          type: string
          enum:
            - dial
        params:
          anyOf:
            - $ref: '#/components/schemas/CallCreateParamsURL'
            - $ref: '#/components/schemas/CallCreateParamsSWML'
    CallResponse:
      type: object
      required:
        - id
        - from
        - to
        - direction
        - status
        - duration
        - duration_ms
        - billable_duration
        - source
        - type
        - charge
      properties:
        id:
          type: string
          description: The unique identifier of the call on SignalWire. This can be used to update the call programmatically.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        from:
          type: string
          description: The origin number or address.
          example: sip:from-sip@example-112233445566.sip.signalwire.com
        to:
          type: string
          description: The destination number or address.
          example: sip:from-sip@example-112233445567.sip.signalwire.com
        direction:
          type: string
          enum:
            - outbound-api
          description: The direction of the call.
          example: outbound-api
        status:
          type: string
          enum:
            - answered
            - queued
            - initiated
            - ringing
            - ending
            - ended
          description: The status of the call.
          example: queued
        duration:
          type: integer
          description: The duration of the call in seconds.
          example: 60
        duration_ms:
          type: integer
          description: The duration of the call in milliseconds.
          example: 60000
        billable_duration:
          type: integer
          description: The billable duration of the call in seconds.
          example: 60
        source:
          type: string
          enum:
            - realtime_api
          description: Source of this call.
          example: realtime_api
        type:
          type: string
          enum:
            - relay_pstn_call
            - relay_sip_call
            - relay_webrtc_call
          description: Type of this call.
          example: relay_sip_call
        charge:
          type: array
          items:
            $ref: '#/components/schemas/ChargeDetails'
          description: Details on charges associated with this call.
    CallUpdate422Error:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Types.StatusCodes.StatusCode422Error'
      example:
        errors:
          - type: validation_error
            code: missing_required_parameter
            message: url must be a valid http or https url
            attribute: url
            url: https://developer.signalwire.com/rest/signalwire-rest/overview/error-codes#http_url_required
    CallUpdateParamsSWML:
      type: object
      required:
        - id
        - swml
      properties:
        id:
          type: string
          description: The id of an existing call.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        fallback_url:
          type: string
          description: |-
            The Fallback URL to handle the call. 
            This parameter allows you to specify a backup webhook or different route in your code containing SWML instructions for handling the call.
          example: https://example.com/fallback
        status:
          type: string
          enum:
            - canceled
            - completed
          description: Either `canceled` (to cancel a not yet connected call) or `completed` (to end a call that is in progress).
          example: canceled
        swml:
          type: string
          description: Inline SWML, passed as a string, containing SWML instructions for handling the call. Either `url` or `swml` must be included for a new call.
          example: "{'version': '1.0.0', 'sections': { 'main': [{ 'answer': { 'max_duration': 60 }},{ 'play': { 'urls': ['silence:2', 'say:Hello from SignalWire!']}}]}}"
      title: Update a call with SWML
    CallUpdateParamsURL:
      type: object
      required:
        - id
        - url
      properties:
        id:
          type: string
          description: The id of an existing call.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        fallback_url:
          type: string
          description: |-
            The Fallback URL to handle the call. 
            This parameter allows you to specify a backup webhook or different route in your code containing SWML instructions for handling the call.
          example: https://example.com/fallback
        status:
          type: string
          enum:
            - canceled
            - completed
          description: Either `canceled` (to cancel a not yet connected call) or `completed` (to end a call that is in progress).
          example: canceled
        url:
          type: string
          description: |-
            The URL to handle the call. This parameter allows you to specify a webhook or different route in your code containing SWML instructions for handling the call.
            Either `url` or `swml` must be included for a new call.
          example: https://example.com/swml
      title: Update a call with a URL
    CallUpdateRequest:
      type: object
      required:
        - command
        - params
      properties:
        command:
          type: string
          enum:
            - update
        params:
          oneOf:
            - $ref: '#/components/schemas/CallUpdateParamsURL'
            - $ref: '#/components/schemas/CallUpdateParamsSWML'
    ChargeDetails:
      type: object
      required:
        - description
        - amount
      properties:
        description:
          type: string
          description: Description for this charge.
        amount:
          type: integer
          description: Charged amount.
    Types.StatusCodes.StatusCode422Error:
      type: object
      required:
        - type
        - code
        - message
        - attribute
        - url
      properties:
        type:
          type: string
          description: Error type.
        code:
          type: string
          description: Error code.
        message:
          type: string
          description: Error details.
        attribute:
          type: string
          description: Request parameter associated with this error.
        url:
          type: string
          description: Link to developer resource for this error.
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
servers:
  - url: https://{space_name}.signalwire.com/api/calling
    description: Endpoint
    variables:
      space_name:
        default: '{Your_Space_Name}'
