FROM node:24-slim

RUN npm install -g fern-api pnpm

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY fern/ ./fern/

EXPOSE 3000 3001

CMD ["fern", "docs", "dev"]
