services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ~/.fern/token:/root/.fern/token:ro
      - ~/.fern/id:/root/.fern/id:ro
    ports:
      - "3000:3000"
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./fern
          target: /app/fern
