# Global settings applied to the whole site.
[build]
  base = ""
  command = "yarn install && yarn build"
  publish = "website/build/"
  environment = { NODE_VERSION = "22", NODE_OPTIONS = "--max_old_space_size=4096", WEBPACK_URL_LOADER_LIMIT = "512", DOCUSAURUS_SSG_WORKER_THREAD_COUNT = "3", DOCUSAURUS_SSG_WORKER_THREAD_TASK_SIZE = "10" }

# All deploys from the main branch
# will inherit these settings.
[context.main]
  base = ""
  command = "yarn install && yarn build"
  publish = "website/build/"
