# Global settings applied to the whole site.
[build]
  base = ""
  command = "yarn install && yarn build"
  publish = "website/build/"
  environment = { NODE_VERSION = "20", NODE_OPTIONS = "--max_old_space_size=16384", WEBPACK_URL_LOADER_LIMIT = "512" }

# All deploys from the main branch
# will inherit these settings.
[context.main]
  base = ""
  command = "yarn install && yarn build"
  publish = "website/build/"
