# Global settings applied to the whole site.
[build]
  command = "npm i && npm run build"
  publish = "build/"
  environment = { NODE_VERSION = "20", NODE_OPTIONS = "--max_old_space_size=4096", WEBPACK_URL_LOADER_LIMIT = "512" }

# All deploys from the main branch
# will inherit these settings.
[context.main]
  command = "echo Skipping build && mkdir empty"
  publish = "empty/"
