import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const agentsSdkSidebar: SidebarsConfig = {
  agentsSdkSidebar: [
    { type: "autogenerated", dirName: "." }
  ],
};

export default agentsSdkSidebar;
