# Datasphere API - outputs to fern/apis/Datasphere
extends: ../../tspconfig.yaml
emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{cwd}/../../../fern/apis/Datasphere"
    output-file: openapi.yaml
