name: '404'
description: Report a broken link on a SignalWire documentation site.
title: "[404] - "
labels: ["team/developer-experience", "type/chore", "status/needs-triage"]
body: 
  - type: markdown
    attributes:
      value: |
        Thanks for helping us keep our documentation up to date!
        > [!CAUTION]
        > Authors should avoid changing slugs (URLs) of docs whenever possible, and closely follow the instructions in the [wiki article on slugs](https://github.com/signalwire/signalwire-docs/wiki/Slug:-Best-practices#never-change-slugs) when a change is unavoidable.
  - type: input
    id: broken-link
    attributes:
      label: Broken link
      description: Paste the full broken link here.
      placeholder: https://developer.signalwire.com/broken/link
    validations:
      required: true
  - type: textarea
    id: where-found
    attributes:
      label: Link location
      description: |
        Where did you find this link?
        Be sure to include a case number if the link was discovered in a support ticket.
      placeholder: Google search, docs site, customer, etc.
      value: 
    validations:
      required: true
  - type: input
    id: correct-link
    attributes:
      label: Correct link
      description: What's the correct link?
      placeholder: https://developer.signalwire.com/correct/link
    validations:
      required: false
  - type: textarea
    id: other-info
    attributes:
      label: Other info
      description: Any additional context
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for catching that!