# Root configuration with emitter options
# Child configs will extend this and specify which emitter to use
# All OpenAPI specs will be output to: fern/docs/openapi-specs/
output-dir: "{project-root}/../openapi-specs"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{output-dir}"
    "new-line": lf
    "omit-unreachable-types": true
    "version": "3.1.0"

  "@typespec/json-schema":
    emitter-output-dir: "{output-dir}/json-schema"
    file-type: "json"
    seal-object-schemas: true
