openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    AddressChannel:
      anyOf:
        - $ref: '#/components/schemas/AudioChannel'
        - $ref: '#/components/schemas/MessagingChannel'
        - $ref: '#/components/schemas/VideoChannel'
    AudioChannel:
      type: object
      required:
        - audio
      properties:
        audio:
          type: string
          example: /external/resource_name?channel=audio
          description: Audio Channel of Fabric Address
    CXMLWebhookID:
      type: object
      required:
        - id
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: Unique ID of a CXML Webhook.
    DisplayTypes:
      type: string
      enum:
        - app
        - room
        - call
        - subscriber
      description: DisplayTypes
    HandleCallsUsing:
      type: string
      enum:
        - script
        - external_url
      description: Indicates whether the call will be handled by a script or an external url.
    MessagingChannel:
      type: object
      required:
        - messaging
      properties:
        messaging:
          type: string
          example: /external/resource_name?channel=messaging
          description: Messaging Channel of Fabric Address
    StatusCode403:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - Forbidden
    VideoChannel:
      type: object
      required:
        - video
      properties:
        video:
          type: string
          example: /external/resource_name?channel=video
          description: Video Channel of Fabric Address
    uuid:
      type: string
      format: uuid
      description: Universal Unique Identifier.
