import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const agentsSdkSidebar: SidebarsConfig = {
  agentsSdkSidebar: [
    { type: "autogenerated", dirName: "swml/agents-sdk" }
  ],
};

export default agentsSdkSidebar;