import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sdksSidebar: SidebarsConfig = {
  sdksSidebar: [
    {
      type: "category",
      label: "SDKs",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "sdks/01-overview" }],
    },
    {
      type: "category",
      label: "SDK Reference",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [
        {
          type: "link",
          href: "/sdks/browser-sdk",
          label: "RELAY Browser SDK",
        },
        {
          type: "link",
          href: "/sdks/realtime-sdk",
          label: "RELAY Realtime SDK",
        },
        {
          type: "doc",
          id: "sdks/reference/video-conference-appkit/index",
          label: "Video Conference AppKit",
        },
        {
          type: "ref",
          id: "swml/get-started/index",
          label: "SWML",
        },
      ],
    }
  ],
};

export default sdksSidebar;