import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sdksSidebar: SidebarsConfig = {
  sdksSidebar: [
    {
      type: "category",
      label: "Overview",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "sdks/01-overview" }],
    },
    {
      type: "category",
      label: "SDK Reference",
      collapsible: false,
      collapsed: false,
      className: "menu-category",
      items: [
        {
          type: "link",
          href: "/sdks/browser-sdk",
          label: "Browser SDK",
        },
        {
          type: "link",
          href: "/sdks/realtime-sdk",
          label: "Realtime SDK",
        }
      ],
    }
  ],
};

export default sdksSidebar;