export interface TagConfig {
  startingDirs: string[];
  allowedExtensions: string[];
  pathTags: Record<string, string[]>;
}

export const config: TagConfig = {
  // Starting directories for the tag system
  startingDirs: [
    "../../website/docs/main",
    "../../website/docs/browser-sdk",
    "../../website/docs/realtime-sdk",
  ],

  // File extensions to process
  allowedExtensions: [".md", ".mdx"],

  // Path-to-tags mapping
  // Add your tags for each path below
  // More specific paths take precedence over general ones
  pathTags: {
    "/cantina": ["tools"],
    "/cantina/user-guide": ["guides"],
    "/compatibility-api": ["compatibility-api"],
    "/compatibility-api/api-reference": ["rest-api"],
    "/compatibility-api/api-reference/rest-client-sdks": ["rest-api"],
    "/compatibility-api/api-reference/rest-client-sdks/methods": ["rest-api"],
    "/compatibility-api/cxml": ["cxml"],
    "/compatibility-api/cxml/fax": ["cxml", "fax"],
    "/compatibility-api/cxml/messaging": ["cxml", "messaging"],
    "/compatibility-api/cxml/voice": ["cxml", "voice"],
    "/compatibility-api/cxml/voice/pay": ["cxml", "voice"],
    "/compatibility-api/guides": ["compatibility-api", "guides"],
    "/compatibility-api/guides/fax": ["compatibility-api", "guides", "fax"],
    "/compatibility-api/guides/general": ["compatibility-api", "guides"],
    "/compatibility-api/guides/general/phone-numbers": ["compatibility-api", "guides"],
    "/compatibility-api/guides/messaging": ["compatibility-api", "guides", "messaging"],
    "/compatibility-api/guides/messaging/general": ["compatibility-api", "guides", "messaging"],
    "/compatibility-api/guides/messaging/python": ["compatibility-api", "guides", "messaging", "python"],
    "/compatibility-api/guides/voice": ["compatibility-api", "guides", "voice"],
    "/compatibility-api/guides/voice/general": ["compatibility-api", "guides", "voice"],
    "/compatibility-api/guides/voice/nodejs": ["compatibility-api", "guides", "voice"],
    "/compatibility-api/guides/voice/python": ["compatibility-api", "guides", "voice", "python"],
    "/compatibility-api/guides/voice/ruby": ["compatibility-api", "guides", "voice"],
    "/compatibility-api/sdks": ["compatibility-api"],
    "/events": ["guides"],
    "/events/demos": ["guides"],
    "/events/demos/server": ["guides"],
    "/events/demos/server/ai-cal": ["guides"],
    "/events/demos/server/esp8266-sensor-bot": ["guides"],
    "/events/demos/server/flos-flowers-2": ["guides"],
    "/events/demos/server/mfa": ["guides"],
    "/events/demos/server/restaurant-reservation": ["guides"],
    "/events/demos/server/room-service": ["guides"],
    "/events/demos/server/tier-1-support": ["guides"],
    "/events/demos/serverless": ["guides"],
    "/events/demos/serverless/admin-assistant": ["guides"],
    "/events/demos/serverless/virtual-flowers-demo": ["guides"],
    "/events/demos/serverless/weather-bot-demo": ["guides"],
    "/events/hackathons": ["guides"],
    "/events/hackathons/cluecon-2024": ["guides"],
    "/events/livewire": ["guides"],
    "/events/livewire/smart-biz-ai": ["guides"],
    "/events/livewire/swaig-plus-zendesk": ["guides"],
    "/events/livewire/swaig-plus-zendesk/functions": ["guides"],
    "/home": ["home"],
    "/home/calling": ["home", "voice"],
    "/home/calling/ai": ["home", "voice"],
    "/home/calling/ai/get-started": ["home", "voice", "guides"],
    "/home/calling/ai/guides": ["home", "voice", "guides"],
    "/home/calling/ai/pom": ["home", "voice"],
    "/home/calling/fax": ["home", "fax"],
    "/home/calling/fax/getting-started": ["home", "fax", "guides"],
    "/home/calling/video": ["home", "video"],
    "/home/calling/video/get-started": ["home", "video", "guides"],
    "/home/calling/video/guides": ["home", "video", "guides"],
    "/home/calling/voice": ["home", "voice"],
    "/home/calling/voice/getting-started": ["home", "voice", "guides"],
    "/home/calling/voice/guides": ["home", "voice", "guides"],
    "/home/calling/voice/sip": ["home", "voice"],
    "/home/calling/voice/tts": ["home", "voice"],
    "/home/messaging": ["home", "messaging"],
    "/home/messaging/chat": ["home", "messaging"],
    "/home/messaging/chat/getting-started": ["home", "messaging", "guides"],
    "/home/messaging/chat/guides": ["home", "messaging", "guides"],
    "/home/messaging/sms": ["home", "messaging"],
    "/home/messaging/sms/campaign-registry": ["home", "messaging"],
    "/home/messaging/sms/getting-started": ["home", "messaging", "guides"],
    "/home/messaging/sms/guides": ["home", "messaging", "guides"],
    "/home/overview": ["home"],
    "/home/platform": ["home", "platform"],
    "/home/platform/basics": ["home", "platform"],
    "/home/platform/basics/general": ["home", "platform"],
    "/home/platform/basics/guides": ["home", "platform", "guides"],
    "/home/platform/basics/security-and-compliance": ["home", "platform"],
    "/home/platform/call-fabric": ["home", "platform"],
    "/home/platform/call-fabric/addresses": ["home", "platform"],
    "/home/platform/call-fabric/resources": ["home", "platform"],
    "/home/platform/call-fabric/subscribers": ["home", "platform"],
    "/home/platform/dashboard": ["home", "platform"],
    "/home/platform/dashboard/administration": ["home", "platform"],
    "/home/platform/dashboard/api": ["home", "platform"],
    "/home/platform/dashboard/billing": ["home", "platform"],
    "/home/platform/dashboard/logs": ["home", "platform"],
    "/home/platform/dashboard/navigate": ["home", "platform"],
    "/home/platform/dashboard/phone-numbers": ["home", "platform"],
    "/home/platform/integrations": ["home", "platform"],
    "/home/platform/integrations/carriers": ["home", "platform"],
    "/home/platform/integrations/crm": ["home", "platform"],
    "/home/platform/integrations/dialogflow": ["home", "platform"],
    "/home/platform/integrations/freeswitch": ["home", "platform"],
    "/home/platform/integrations/messaging-services": ["home", "platform", "messaging"],
    "/home/platform/integrations/pbx-systems": ["home", "platform"],
    "/home/platform/integrations/serverless-functions": ["home", "platform"],
    "/home/platform/integrations/softphones": ["home", "platform"],
    "/home/platform/integrations/workflow-tools": ["home", "platform"],
    "/home/platform/phone-numbers": ["home", "platform"],
    "/home/platform/phone-numbers/getting-started": ["home", "platform", "guides"],
    "/home/platform/phone-numbers/guides": ["home", "platform", "guides"],
    "/home/tools": ["home", "tools"],
    "/home/tools/c2c": ["home", "tools"],
    "/home/tools/call-flow-builder": ["home", "tools"],
    "/home/tools/call-flow-builder/nodes": ["home", "tools"],
    "/home/tools/call-flow-builder/variables": ["home", "tools"],
    "/home/tools/call-flow-builder/version": ["home", "tools"],
    "/home/tools/swsh": ["home", "tools"],
    "/home/tools/wirestarter": ["home", "tools"],
    "/rest": ["rest-api"],
    "/rest/compatibility-api": ["compatibility-api", "rest-api"],
    "/rest/compatibility-api/endpoints": ["compatibility-api", "rest-api"],
    "/rest/compatibility-api/overview": ["compatibility-api", "rest-api"],
    "/rest/overview": ["rest-api"],
    "/rest/signalwire-rest": ["rest-api"],
    "/rest/signalwire-rest/endpoints": ["rest-api"],
    "/rest/signalwire-rest/endpoints/calling": ["rest-api", "voice"],
    "/rest/signalwire-rest/endpoints/chat": ["rest-api", "messaging"],
    "/rest/signalwire-rest/endpoints/datasphere": ["rest-api"],
    "/rest/signalwire-rest/endpoints/fabric": ["rest-api"],
    "/rest/signalwire-rest/endpoints/fax": ["rest-api", "fax"],
    "/rest/signalwire-rest/endpoints/logs": ["rest-api"],
    "/rest/signalwire-rest/endpoints/messaging": ["rest-api", "messaging"],
    "/rest/signalwire-rest/endpoints/project": ["rest-api"],
    "/rest/signalwire-rest/endpoints/pubsub": ["rest-api"],
    "/rest/signalwire-rest/endpoints/space": ["rest-api"],
    "/rest/signalwire-rest/endpoints/video": ["rest-api", "video"],
    "/rest/signalwire-rest/endpoints/voice": ["rest-api", "voice"],
    "/rest/signalwire-rest/guides": ["rest-api", "guides"],
    "/rest/signalwire-rest/guides/campaign-registry": ["rest-api", "guides", "messaging"],
    "/rest/signalwire-rest/guides/datasphere": ["rest-api", "guides"],
    "/rest/signalwire-rest/overview": ["rest-api"],
    "/sdks": ["guides"],
    "/sdks/01-overview": ["guides"],
    "/swml": ["swml"],
    "/swml/agents-sdk": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/api": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/advanced": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/contexts": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/create": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/datamap": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/dynamic-config": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/languages-voices": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/prefabs": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/prompt": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/skills": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/composition/swaig": ["swml", "agents-sdk", "python"],
    "/swml/agents-sdk/get-started": ["swml", "agents-sdk", "python", "guides"],
    "/swml/agents-sdk/guides": ["swml", "agents-sdk", "python", "guides"],
    "/swml/get-started": ["swml", "guides"],
    "/swml/guides": ["swml", "guides"],
    "/swml/guides/AI": ["swml", "guides"],
    "/swml/guides/AI/holiday-special-santa-ai": ["swml", "guides"],
    "/swml/guides/AI/swaig": ["swml", "guides"],
    "/swml/guides/call-whisper": ["swml", "guides"],
    "/swml/guides/creating-ivr-with-swml": ["swml", "guides"],
    "/swml/guides/methods": ["swml", "guides"],
    "/swml/guides/methods/goto-execute-transfer-disambiguation": ["swml", "guides"],
    "/swml/guides/methods/request": ["swml", "guides"],
    "/swml/methods": ["swml"],
    "/swml/methods/ai": ["swml"],
    "/swml/methods/ai/ai_params": ["swml"],
    "/swml/methods/ai/ai_swaig": ["swml"],
    "/swml/methods/ai/prompt": ["swml"],
    "/swml/methods/connect": ["swml"],
    "/swml/methods/live_transcribe": ["swml"],
    "/swml/methods/live_transcribe/action": ["swml"],
    "/swml/methods/live_translate": ["swml"],
    "/swml/methods/live_translate/action": ["swml"],
    "/swml/methods/pay": ["swml"],
    "/swml/methods/pay/parameters": ["swml"],
    "/swml/methods/pay/prompts": ["swml"],

    // Browser SDK paths
    "/browser-sdk": ["browser-sdk"],
    "/browser-sdk/guides": ["browser-sdk", "guides"],
    "/browser-sdk/tech-ref": ["browser-sdk"],

    // Realtime SDK paths
    "/realtime-sdk": ["realtime-sdk"],
    "/realtime-sdk/guides": ["realtime-sdk", "guides"],
    "/realtime-sdk/tech-ref": ["realtime-sdk"],
    "/realtime-sdk/language": ["realtime-sdk"],
  },
};
