import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const callFlowBuilderSidebar: SidebarsConfig = {
  callFlowBuilderSidebar: [
    { type: "autogenerated", dirName: "call-flow-builder" }
  ],
};

export default callFlowBuilderSidebar;
