import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const cantinaSidebar: SidebarsConfig = {
  cantinaSidebar: [{ type: "autogenerated", dirName: "cantina" }],
};

export default cantinaSidebar;