import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const compatibilityAPI: SidebarsConfig = {
  compatibilityAPI: [
    {
      type: "category",
      label: "Compatibility API",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          id: "compatibility-api/index",
          label: "Overview",
        },
        {
          type: "link",
          label: "Compatibility REST API Reference",
          href: "https://developer.signalwire.com/rest/compatibility-api",
        },
      ],
    },
    {
      type: "category",
      label: "cXML",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml",
        },
      ],
    },
    {
      type: "category",
      label: "Libraries & SDKs",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          id: "compatibility-api/sdks/index",
          label: "Overview",
        },
        {
          type: "autogenerated",
          dirName: "compatibility-api/api-reference/rest-client-sdks",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/guides",
        },
      ],
    },
  ],
};

export default compatibilityAPI;