import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const compatibilityApiSidebars: SidebarsConfig = {
  // Overview Sidebar
  compatibilityApiOverviewSidebar: [
    {
      type: "category",
      label: "Compatibility API",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          id: "compatibility-api/index",
          label: "Overview",
        }
      ],
    },
  ],

  // cXML Sidebar
  compatibilityApiReferenceSidebar: [
    {
      type: "category",
      label: "cXML",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/cxml",
        },
      ],
    },
  ],

  // Client Libraries Sidebar
  compatibilityApiClientLibrariesSidebar: [
    {
      type: "category",
      label: "REST Client Libraries",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          id: "compatibility-api/sdks/index",
          label: "Overview",
        },
        {
          type: "autogenerated",
          dirName: "compatibility-api/api-reference/rest-client-sdks",
        }
      ],
    },
  ],

  // Guides Sidebar
  compatibilityApiGuidesSidebar: [
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "compatibility-api/guides",
        },
      ],
    },
  ],

  // REST API Sidebar
  apiCompatibilitySidebar: [
    {
      type: "category",
      label: "Compatibility REST API",
      collapsible: false,
      className: "menu-category",
      link: {
        type: "generated-index",
        title: "Compatibility REST API",
        description:
          "This API may look very similar to other, existing APIs you've used before — on purpose! The SignalWire Compatibility REST API is designed to make migrating your existing phone or messaging application easy and quick, while giving you access to our next generation APIs and endpoints to help you take your application to the next level.",
        slug: "/rest/compatibility-api",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "rest/compatibility-api/overview",
        },
        {
          type: "category",
          label: "REST Endpoints ",
          link: {
            type: "generated-index",
            title: "Available Compatibility REST API Endpoints",
            description:
              "Below are the available Compatibility REST APIs categorized by their endpoints.",
            slug: "/rest/compatibility-api/endpoints",
          },
          items: require("../../../docs/main/rest/compatibility-api/endpoints/sidebar"),
        },
      ],
    },
  ],
};

export default compatibilityApiSidebars;
