import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const swmlSidebars: SidebarsConfig = {
  // Overview/Get Started Sidebar
  swmlOverviewSidebar: [
    {
      type: "category",
      label: "Get started",
      collapsible: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "swml/get-started" }],
    },
  ],

  // Guides Sidebar
  swmlGuidesSidebar: [
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "swml/guides" }],
    },
  ],

  // Methods/Reference Sidebar
  swmlMethodsSidebar: [
    {
      type: "category",
      label: "Methods",
      collapsible: false,
      className: "menu-category",
      items: [{ type: "autogenerated", dirName: "swml/methods" }],
    },
  ],
};

export default swmlSidebars;