import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const agentsSdkManualSidebar: SidebarsConfig = {
  agentsSdkManualSidebar: [
    { type: "autogenerated", dirName: "." }
  ],
};

export default agentsSdkManualSidebar;
