openapi: 3.0.0
info:
  title: Chat API
  description: An API to programmatically create your own Chat Applications.
  version: 0.0.0
tags:
  - name: Tokens
paths:
  /tokens:
    post:
      operationId: create_chat_token
      summary: Generate a new Chat Token
      description: |-
        Generate a Chat Token to be used to authenticate clients to the Chat Service.


        #### Permissions

        The API token must include the following scopes: `Chat`.
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatToken'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode401'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode404'
        '422':
          description: The request contains invalid parameters. See errors for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatToken422Error'
      tags:
        - Tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewChatToken'
security:
  - SignalWireBasicAuth: []
components:
  schemas:
    ChatChannel:
      type: object
      additionalProperties:
        type: object
        properties:
          read:
            type: boolean
            description: Gives the token read access to the channel.
            example: true
          write:
            type: boolean
            description: Gives the token write access to the channel.
            example: false
        required:
          - read
          - write
      description: |-
        User-defined channel names. Each channel is a object with `read` and `write` properties.
        Max of 500 channels inside main `channels`. Either `read`, `write`, or both are required inside each channel and default to `false`.
        Each channel name can be up to 250 characters. Must be valid JSON.
      example:
        channel1:
          read: true
          write: true
        channel2:
          read: true
          write: false
    ChatState:
      type: object
      additionalProperties: {}
      description: An arbitrary JSON object available to store stateful application information in. Must be valid JSON and have a maximum size of 2,000 characters.
      example:
        key: value
        key2: value2
    ChatToken:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: The generated Chat Token.
          example: eyJ0eXAiOiJWUlQiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2MjIxMjAxMjMsI...wMCwicnNlIjo5MDB9-BqG-DqC5LhpsdMWEFjhVkTBpQ
    ChatToken422Error:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Types.StatusCodes.RestApiErrorItem'
          description: List of validation errors.
      description: The request contains invalid parameters. See errors for details.
      example:
        statusCode: 422
        errors:
          - type: validation_error
            code: missing_required_parameter
            message: A required parameter is missing from the request. Please refer to the technical reference for a complete list of parameters.
            attribute: ttl
            url: https://developer.signalwire.com/rest/signalwire-rest/overview/error-codes#field-missing-required-parameter
    NewChatToken:
      type: object
      required:
        - ttl
        - channels
      properties:
        ttl:
          type: integer
          minimum: 1
          maximum: 43200
          description: The maximum time, in minutes, that the access token will be valid for. Between 1 and 43,200 (30 days).
          example: 60
        channels:
          $ref: '#/components/schemas/ChatChannel'
        member_id:
          type: string
          description: The unique identifier of the member. Up to 250 characters. If not specified, a random UUID will be generated.
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        state:
          allOf:
            - $ref: '#/components/schemas/ChatState'
          description: An arbitrary JSON object available to store stateful application information in. Must be valid JSON and have a maximum size of 2,000 characters.
    Types.StatusCodes.RestApiErrorItem:
      type: object
      required:
        - type
        - code
        - message
        - url
      properties:
        type:
          type: string
          description: The category of error.
          example: validation_error
        code:
          type: string
          description: A specific error code.
          example: invalid_parameter
        message:
          type: string
          description: A description of what caused the error.
          example: Name must be present
        attribute:
          type: string
          nullable: true
          description: The request parameter that caused the error, if applicable.
          example: name
        url:
          type: string
          description: A link to documentation about this error.
          example: https://developer.signalwire.com/rest/signalwire-rest/overview/error-codes#invalid_parameter
      description: Details about a specific error.
    Types.StatusCodes.StatusCode401:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - Unauthorized
      description: Access is unauthorized.
    Types.StatusCodes.StatusCode404:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          enum:
            - Not Found
      description: The server cannot find the requested resource.
  securitySchemes:
    SignalWireBasicAuth:
      type: http
      scheme: Basic
      description: |-
        SignalWire Basic Authentication using Project ID and API Token.

        The client sends HTTP requests with the Authorization header containing
        the word Basic followed by a space and a base64-encoded string of project_id:token.
        The project ID will be used as the username and the API token as the password.

        Example:
        ```
        Authorization: Basic base64(project_id:token)
        ```
      x-fern-basic:
        username:
          name: project_id
          env: SIGNALWIRE_PROJECT_ID
        password:
          name: token
          env: SIGNALWIRE_API_TOKEN
servers:
  - url: https://{space_name}.signalwire.com/api/chat
    description: Endpoint
    variables:
      space_name:
        default: '{Your_Space_Name}'
