openapi: 3.0.3
info:
  version: 1.0.0
  title: Calling API
  description: >-
    An API to programmatically access information about SignalWire calling
    activity.
  termsOfService: https://signalwire.com/legal/signalwire-cloud-agreement
externalDocs:
  url: https://developers.signalwire.com
  description: Find more information about this and other SignalWire APIs.
servers:
  - url: https://{space_name}.signalwire.com/api/calling
    variables:
      space_name:
        default: YOUR_SPACE
        description: Your SignalWire Space's subdomain.
security:
  - basic_auth: []
components:
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
paths:
  /calls:
    post:
      operationId: create_call
      summary: Create a Call
      description: >
        To create a new Call, you send a `POST` request to the Call resource
        with a payload including a `dial` command and additional nested
        `params`.
      tags:
        - Calls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: The command to send to the Calling API (`dial`)
                  example: dial
                params:
                  type: object
                  properties:
                    from:
                      type: string
                      description: >-
                        The address that initiated the call. Can be either a
                        E.164 formatted number (`+xxxxxxxxxxx`), or a SIP
                        endpoint (`sip:xxx@yyy.zzz`).
                      example: sip:from-sip@example-112233445566.sip.signalwire.com
                    to:
                      type: string
                      description: >-
                        The address that received the call. Can be either a
                        E.164 formatted number (`+xxxxxxxxxxx`), or a SIP
                        endpoint (`sip:xxx@yyy.zzz`).
                      example: sip:to-sip@example-112233445566.sip.signalwire.com
                    caller_id:
                      type: string
                      description: >-
                        The number, in E.164 format, or identifier of the
                        caller.
                      example: Billing Dept
                    url:
                      type: string
                      description: >-
                        The URL to handle the call. This parameter allows you to
                        specify a webhook or different route in your code
                        containing SWML instructions for handling the call.
                        Either `url` or `swml` must be included for a new call.
                      example: http://your-application.com/swml.json
                    fallback_url:
                      type: string
                      description: >-
                        The Fallback URL to handle the call. This parameter
                        allows you to specify a backup webhook or different
                        route in your code containing SWML instructions for
                        handling the call.
                      example: http://your-application.com/swml.json
                    swml:
                      type: string
                      description: >-
                        Inline SWML, passed as a string, containing SWML
                        instructions for handling the call. Either `url` or
                        `swml` must be included for a new call.
                      example: >-
                        {
                          "version": "1.0.0",
                          "sections": {
                            "main": [
                              {
                                "answer": {
                                  "max_duration": 60
                                }
                              },
                              {
                                "play": {
                                  "urls": [
                                    "silence:2",
                                    "say:Hello from SignalWire!"
                                  ]
                                }
                              }
                            ]
                          }
                        }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      id:
                        type: string
                        description: >-
                          The unique identifier of the call on SignalWire. This
                          can be used to update the call programmatically.
                        format: uuid
                    required:
                      - id
                  - type: object
                    properties:
                      from:
                        type: string
                        description: The origin number or address.
                        example: sip:from-sip@example-112233445566.sip.signalwire.com
                      to:
                        type: string
                        description: The destination number or address.
                        example: sip:to-sip@example-112233445566.sip.signalwire.com
                      direction:
                        type: string
                        description: The direction of the call.
                        example: outbound-api
                      status:
                        type: string
                        description: The status of the call.
                        example: queued
                      duration:
                        type: integer
                        description: The duration of the call in seconds.
                      duration_ms:
                        type: integer
                        description: The duration of the call in milliseconds.
                      billing_ms:
                        type: integer
                        description: The billable duration of the call in seconds.
                      source:
                        type: string
                        description: Source of this call.
                        example: realtime_api
                      type:
                        type: string
                        description: Type of this call.
                        example: relay_sip_call
                      url:
                        type: string
                        description: >-
                          URL for the resource associated with this call (if
                          available)
                      charge:
                        type: number
                        description: The charge in dollars.
                        example: '0.01'
                      charge_details:
                        type: array
                        description: Details on charges associated with this call.
                        items:
                          type: object
                          properties:
                            description:
                              type: string
                              description: Description for this charge.
                            charge:
                              type: number
                              description: Charged amount.
                        example: []
    put:
      operationId: update_call
      summary: Update a Call
      description: >
        To update an existing Call, you send a `PUT` request to the Call
        resource with a payload including an `update` command and additional
        nested `params`.
      tags:
        - Calls
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  description: The command to send to the Calling API (`update`)
                  example: update
                params:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: The id of an existing call.
                    url:
                      type: string
                      description: >-
                        The URL to handle the call. This parameter allows you to
                        specify a webhook or different route in your code
                        containing SWML instructions for handling the call.
                        Either `url` or `swml` must be included for a new call.
                      example: http://your-application.com/swml.json
                    fallback_url:
                      type: string
                      description: >-
                        The Fallback URL to handle the call. This parameter
                        allows you to specify a backup webhook or different
                        route in your code containing SWML instructions for
                        handling the call.
                      example: http://your-application.com/swml.json
                    swml:
                      type: string
                      description: >-
                        Inline SWML, passed as a string, containing SWML
                        instructions for handling the call. Either `url` or
                        `swml` must be included for a new call.
                      example: >-
                        ["answer",{"play":["silence:2","say:Hello from
                        SignalWire!"]}]
                    status:
                      type: string
                      description: >-
                        Either `canceled` (to cancel a not yet connected call)
                        or `complete` (to end a call that is in progress).
                        Cannot be used with other options.
                      example: complete
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      id:
                        type: string
                        description: >-
                          The unique identifier of the call on SignalWire. This
                          can be used to update the call programmatically.
                        format: uuid
                    required:
                      - id
                  - type: object
                    properties:
                      from:
                        type: string
                        description: The origin number or address.
                        example: sip:from-sip@example-112233445566.sip.signalwire.com
                      to:
                        type: string
                        description: The destination number or address.
                        example: sip:to-sip@example-112233445566.sip.signalwire.com
                      direction:
                        type: string
                        description: The direction of the call.
                        example: outbound-api
                      status:
                        type: string
                        description: The status of the call.
                        example: queued
                      duration:
                        type: integer
                        description: The duration of the call in seconds.
                      duration_ms:
                        type: integer
                        description: The duration of the call in milliseconds.
                      billing_ms:
                        type: integer
                        description: The billable duration of the call in seconds.
                      source:
                        type: string
                        description: Source of this call.
                        example: realtime_api
                      type:
                        type: string
                        description: Type of this call.
                        example: relay_sip_call
                      url:
                        type: string
                        description: >-
                          URL for the resource associated with this call (if
                          available)
                      charge:
                        type: number
                        description: The charge in dollars.
                        example: '0.01'
                      charge_details:
                        type: array
                        description: Details on charges associated with this call.
                        items:
                          type: object
                          properties:
                            description:
                              type: string
                              description: Description for this charge.
                            charge:
                              type: number
                              description: Charged amount.
                        example: []
