import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const browserSdkSidebars: SidebarsConfig = {
  // Getting Started Sidebar
  browserSdkOverviewSidebar: [
    {
      type: "category",
      label: "Browser SDK",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "doc",
          label: "Overview",
          id: "index"
        }
      ]
    },
  ],

  // Technical Reference Sidebar
  browserSdkReferenceSidebar: [
    {
      type: "category",
      label: "Technical Reference",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "tech-ref"
        }
      ]
    },
  ],

  // Guides Sidebar
  browserSdkGuidesSidebar: [
    {
      type: "category",
      label: "Guides",
      collapsible: false,
      className: "menu-category",
      items: [
        {
          type: "autogenerated",
          dirName: "guides"
        }
      ]
    },
  ],
};

export default browserSdkSidebars;