name: Convert Team Review to Individual Assignments

on:
  pull_request:
    types: [ review_requested ]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign_reviewers_from_team:
    runs-on: ubuntu-latest
    if: ${{ github.event.requested_team.name == 'eng-prime-review'}}
    env:
      GH_TOKEN: ${{ secrets.PRIME_REVIEW_GITHUB_TOKEN }}
      REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - run: echo "A review was requested from eng-prime-review"

      - name: Get usernames for all members in the requested team excluding the PR author
        id: get-members
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"

          echo "Retrieving all members in eng-prime-review.."
          MEMBERS=$(curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer $GH_TOKEN" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/orgs/signalwire/teams/eng-prime-review/members)

          echo "Extracting usernames from response and filtering out PR author from list.."
          MEMBER_USERNAMES=$(echo $MEMBERS | jq -c '[.[] | .login | select(. != "'$PR_AUTHOR'")]')

          echo "members=$MEMBER_USERNAMES" >> $GITHUB_ENV

      - name: Assign each team member for review
        run: |
          source $GITHUB_ENV
          PAYLOAD=$(jq -n --argjson reviewers "$members" '{"reviewers": $reviewers}')

          echo "Assigning each member in eng-prime-review as a reviewer.."
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers \
            -d "$PAYLOAD"

      - name: Remove Team Review Request
        run: |
          source $GITHUB_ENV
          PAYLOAD=$(jq -n --argjson reviewers '[]' --argjson team_reviewers '["eng-prime-review"]' '{"reviewers": $reviewers, "team_reviewers": $team_reviewers}')
          echo $PAYLOAD

          echo "Removing review request for team eng-prime-review.."
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/requested_reviewers \
            -d "$PAYLOAD"
