name: Check OpenAPI Specs

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write  # Needed for commenting on PRs

jobs:
  check-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install typescript ts-node @types/node axios form-data
          
      - name: Generate report
        id: generate-report
        env:
          RATEMYOPENAPI_KEY: ${{ secrets.RATEMYOPENAPI_KEY }}
        run: |
          # Use tee to show output in real-time while also capturing it
          npx ts-node scripts/generate-matrix.ts 2>&1 | tee /dev/tty | {
            REPORT=$(cat)
            if [ $? -ne 0 ]; then
              echo "Failed to generate report"
              exit 1
            fi
            echo "report<<EOF" >> $GITHUB_OUTPUT
            echo "$REPORT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          }

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        continue-on-error: true  # Don't fail if no comment is found
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: "OpenAPI Specification Analysis"

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id || '' }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.generate-report.outputs.report }}
          edit-mode: replace 