name: publish-docs

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/heads/main') && github.run_number > 1 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: yarn install

      - name: Build TypeSpec specifications
        run: yarn build:specs

      - name: Validate Fern configuration
        run: yarn fern-check
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}

      - name: Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: npx fern generate --docs --log-level debug
