name: Test Matrix Generation

on:
  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install typescript ts-node @types/node
        
      - name: Generate matrix
        id: generate-matrix
        run: npx ts-node scripts/generate-matrix.ts > matrix.json && echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT
        
      - name: Validate matrix
        run: |
          # Check if matrix.json exists and is valid JSON
          if [ ! -f matrix.json ]; then
            echo "Error: matrix.json was not generated"
            exit 1
          fi
          
          # Validate the structure of each entry
          jq -c '.[]' matrix.json | while read -r item; do
            name=$(echo "$item" | jq -r '.name')
            path=$(echo "$item" | jq -r '.path')
            
            if [ -z "$name" ] || [ -z "$path" ]; then
              echo "Error: Invalid matrix entry: $item"
              exit 1
            fi
            
            if [ ! -f "$path" ]; then
              echo "Warning: Spec file not found: $path"
            fi
          done
          
          echo "Matrix validation passed!" 